// Generates src/environments/environment.ts from environment variables.
// In Vercel: reads SUPABASE_URL and SUPABASE_ANON_KEY set in the dashboard.
// Locally: reads from .env.local via dotenv (install: npm i -D dotenv).

const fs = require('fs');
const path = require('path');

// Load .env.local for local development (ignored in production)
try {
  require('dotenv').config({ path: path.join(__dirname, '..', '.env.local') });
} catch {
  // dotenv not installed — variables must come from the environment (Vercel)
}

const supabaseUrl = process.env['SUPABASE_URL'];
const supabaseKey = process.env['SUPABASE_ANON_KEY'];

if (!supabaseUrl || !supabaseKey) {
  console.error('ERROR: SUPABASE_URL and SUPABASE_ANON_KEY must be set.');
  process.exit(1);
}

const content = `// Auto-generated by scripts/set-env.js — do not edit manually.
export const environment = {
  production: true,
  supabaseUrl: '${supabaseUrl}',
  supabaseKey: '${supabaseKey}',
};
`;

const outPath = path.join(__dirname, '..', 'src', 'environments', 'environment.ts');
fs.writeFileSync(outPath, content, 'utf8');
console.log('environment.ts generated from environment variables.');
