// Generates src/environments/environment.ts from real environment variables.
// Runs before ng build in Vercel (see package.json "build:vercel").
// For local development, keep the hardcoded values in environment.ts as-is.

const fs = require('fs');
const path = require('path');

const supabaseUrl = process.env['SUPABASE_URL'];
const supabaseKey = process.env['SUPABASE_ANON_KEY'];

if (!supabaseUrl || !supabaseKey) {
  console.error('ERROR: SUPABASE_URL and SUPABASE_ANON_KEY must be set.');
  process.exit(1);
}

const content = `// Auto-generated by scripts/set-env.js — do not edit manually.
export const environment = {
  production: true,
  supabaseUrl: '${supabaseUrl}',
  supabaseKey: '${supabaseKey}',
};
`;

const outPath = path.join(__dirname, '..', 'src', 'environments', 'environment.ts');
fs.writeFileSync(outPath, content, 'utf8');
console.log('environment.ts generated from environment variables.');
